from __future__ import annotations
"""Create LaTeX tables from experiment summaries.

The script is deliberately conservative: it reads *_summary.csv files produced by
run_gaussdist_suite.py, run_digitsdist_suite.py, and run_20newsgroups_distributional.py,
and writes a ready-to-input LaTeX table with final accuracy, AULC, and runtime.
"""

import argparse
from pathlib import Path
import pandas as pd

PRIMARY_METHODS = ["TC-BKME-PMAL", "PMARLDS-lite", "DISTMARGIN", "HILB-DENSITY", "DISTRAND"]


def esc(s: str) -> str:
    return s.replace("_", "\\_")


def group_name(dataset: str) -> str:
    if dataset.startswith("gaussdist_hard"):
        return "Hard Gaussian"
    if dataset.startswith("gaussdist"):
        return "Gaussian"
    if dataset.startswith("digitdist"):
        return "Digits"
    if dataset.startswith("20news"):
        return "20News"
    return "Other"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--results", default="../results")
    p.add_argument("--out", default="../results/tables_for_paper.tex")
    args = p.parse_args()
    results = Path(args.results)
    summary_files = [f for f in sorted(results.glob("*_summary.csv")) if f.name != "all_summary.csv"]
    frames = [pd.read_csv(f) for f in summary_files]
    if not frames:
        raise SystemExit(f"No *_summary.csv files found in {results}")
    df = pd.concat(frames, ignore_index=True)
    df = df.sort_values(["dataset", "method"])
    ranks = pd.read_csv(results / "average_rank.csv") if (results / "average_rank.csv").exists() else None
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        f.write("% Auto-generated by code/make_latex_tables.py\n")
        f.write("\\begin{table*}[t]\n\\centering\n")
        f.write("\\caption{Full benchmark summary generated from the executable experiment suite.}\n")
        f.write("\\label{tab:full-generated-summary}\n")
        f.write("\\small\n")
        f.write("\\begin{tabular}{llccc}\n\\toprule\n")
        f.write("Dataset & Method & Final accuracy & AULC & Runtime (s) \\\\\n")
        f.write("\\midrule\n")
        last = None
        for _, r in df.iterrows():
            if last is not None and r["dataset"] != last:
                f.write("\\midrule\n")
            last = r["dataset"]
            f.write(f"{esc(str(r['dataset']))} & {esc(str(r['method']))} & ")
            f.write(f"{float(r['final_accuracy']):.4f} & {float(r['AULC']):.4f} & {float(r['mean_runtime_seconds']):.4f} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table*}\n")

        compact = df[df["method"].isin(PRIMARY_METHODS)].copy()
        compact["group"] = compact["dataset"].map(group_name)
        compact = compact.groupby(["group", "method"], as_index=False)[
            ["final_accuracy", "AULC", "mean_runtime_seconds"]
        ].mean()
        f.write("\n\\begin{table}[t]\n\\centering\n")
        f.write("\\caption{Compact benchmark summary averaged by dataset family.}\n")
        f.write("\\label{tab:compact-family-summary}\n")
        f.write("\\small\n")
        f.write("\\begin{tabular}{llccc}\n\\toprule\n")
        f.write("Family & Method & Final acc. & AULC & Runtime (s) \\\\\n")
        f.write("\\midrule\n")
        last = None
        for _, r in compact.sort_values(["group", "AULC"], ascending=[True, False]).iterrows():
            if last is not None and r["group"] != last:
                f.write("\\midrule\n")
            last = r["group"]
            f.write(f"{esc(str(r['group']))} & {esc(str(r['method']))} & ")
            f.write(f"{float(r['final_accuracy']):.4f} & {float(r['AULC']):.4f} & {float(r['mean_runtime_seconds']):.4f} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

        if ranks is not None:
            f.write("\n\\begin{table}[t]\n\\centering\n")
            f.write("\\caption{Average AULC rank across all benchmark tasks. Lower is better.}\n")
            f.write("\\label{tab:average-rank-generated}\n")
            f.write("\\small\n")
            f.write("\\begin{tabular}{lc}\n\\toprule\n")
            f.write("Method & Mean rank \\\\\n\\midrule\n")
            for _, r in ranks.iterrows():
                f.write(f"{esc(str(r['method']))} & {float(r['mean_rank']):.2f} \\\\\n")
            f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

        stats_path = results / "pairwise_stats.csv"
        if stats_path.exists():
            stats = pd.read_csv(stats_path)
            stats = stats[stats["comparison"].str.contains("PMARLDS-lite|DISTMARGIN", regex=True)]
            f.write("\n\\begin{table*}[t]\n\\centering\n")
            f.write("\\caption{Pairwise Wilcoxon diagnostics for TC-BKME-PMAL against key baselines. Positive AULC delta favors TC-BKME-PMAL.}\n")
            f.write("\\label{tab:pairwise-stats-generated}\n")
            f.write("\\small\n")
            f.write("\\begin{tabular}{llrrrr}\n\\toprule\n")
            f.write("Dataset & Baseline & $\\Delta$AULC & TC wins & Baseline wins & $p$ \\\\\n")
            f.write("\\midrule\n")
            for _, r in stats.iterrows():
                baseline = str(r["comparison"]).replace("TC-BKME-PMAL vs ", "")
                f.write(f"{esc(str(r['dataset']))} & {esc(baseline)} & ")
                f.write(f"{float(r['mean_aulc_delta']):.4f} & {int(r['tc_wins_aulc'])} & {int(r['other_wins_aulc'])} & {float(r['wilcoxon_p_value']):.3g} \\\\\n")
            f.write("\\bottomrule\n\\end{tabular}\n\\end{table*}\n")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
