from __future__ import annotations
"""Create LaTeX tables from experiment summaries.

This version optionally joins Heart-of-Risk summaries generated by
compute_heart_risk_metrics.py, so the paper can report not only AULC and final
accuracy but also tail-risk behavior of the active-learning trajectory.
"""

import argparse
from pathlib import Path
import pandas as pd


def esc(s: str) -> str:
    return str(s).replace("_", "\\_")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--results", default="../results")
    p.add_argument("--out", default="../results/tables_for_paper.tex")
    args = p.parse_args()
    results = Path(args.results)

    summary_files = [
        f for f in sorted(results.glob("*_summary.csv"))
        if f.name not in {"all_summary.csv", "heart_risk_metrics.csv"}
    ]
    frames = [pd.read_csv(f) for f in summary_files]
    if not frames:
        raise SystemExit(f"No dataset *_summary.csv files found in {results}")
    df = pd.concat(frames, ignore_index=True).drop_duplicates(["dataset", "method"])

    hr_path = results / "heart_risk_metrics.csv"
    has_hr = False
    if hr_path.exists():
        hr = pd.read_csv(hr_path).drop_duplicates(["dataset", "method"])
        df = df.merge(hr, on=["dataset", "method"], how="left")
        has_hr = "CVaR_0.20" in df.columns

    df = df.sort_values(["dataset", "method"])
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        f.write("% Auto-generated by code/make_latex_tables.py\n")
        f.write("\\begin{table*}[t]\n\\centering\n")
        f.write("\\caption{Full benchmark summary generated from the executable experiment suite.}\n")
        f.write("\\label{tab:full-generated-summary}\n")
        f.write("\\small\n")
        if has_hr:
            f.write("\\begin{tabular}{llccccc}\n\\toprule\n")
            f.write("Dataset & Method & Final acc. & AULC & Mean loss & CVaR$_{0.20}$ & Runtime (s) \\\\ \n")
        else:
            f.write("\\begin{tabular}{llccc}\n\\toprule\n")
            f.write("Dataset & Method & Final accuracy & AULC & Runtime (s) \\\\ \n")
        f.write("\\midrule\n")
        last = None
        for _, r in df.iterrows():
            if last is not None and r["dataset"] != last:
                f.write("\\midrule\n")
            last = r["dataset"]
            f.write(f"{esc(r['dataset'])} & {esc(r['method'])} & ")
            if has_hr:
                f.write(f"{float(r['final_accuracy']):.4f} & {float(r['AULC']):.4f} & ")
                f.write(f"{float(r['mean_future_loss']):.4f} & {float(r['CVaR_0.20']):.4f} & ")
                f.write(f"{float(r['mean_runtime_seconds']):.4f} \\\\ \n")
            else:
                f.write(f"{float(r['final_accuracy']):.4f} & {float(r['AULC']):.4f} & {float(r['mean_runtime_seconds']):.4f} \\\\ \n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table*}\n")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
